# Generated by Django 6.0.4 on 2026-05-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=100)),
                ('ge_brand', models.CharField(max_length=50)),
                ('ge_purchase_date', models.DateField()),
                ('ge_condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('mem_first_name', models.CharField(max_length=50)),
                ('mem_last_name', models.CharField(max_length=50)),
                ('mem_email', models.EmailField(max_length=254, unique=True)),
                ('mem_join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('duration_months', models.PositiveIntegerField()),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gym_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_num', models.CharField(max_length=20)),
                ('unit_status', models.CharField(default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_type', models.CharField(max_length=50)),
                ('sp_hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vis_first_name', models.CharField(max_length=50)),
                ('vis_last_name', models.CharField(max_length=50)),
                ('visit_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club_app.member')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club_app.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='MemberPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='club_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='club_app.membershipplan'),
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_start_time', models.TimeField()),
                ('bk_end_time', models.TimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='club_app.booking')),
                ('play_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='club_app.playunit')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_first_name', models.CharField(max_length=50)),
                ('staff_last_name', models.CharField(max_length=50)),
                ('staff_role', models.CharField(max_length=50)),
                ('staff_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintains_facilities', models.ManyToManyField(blank=True, related_name='maintained_by_staff', to='club_app.sportsfacility')),
            ],
        ),
        migrations.AddField(
            model_name='playunit',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='club_app.sportsfacility'),
        ),
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='club_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='club_app.booking')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='club_app.member')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='club_app.membershipplan')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='club_app.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='club_app.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='GymTrainer',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='club_app.staff')),
                ('trainer_start_time', models.TimeField()),
                ('trainer_end_time', models.TimeField()),
                ('maintains_equipment', models.ManyToManyField(blank=True, related_name='maintained_by_trainers', to='club_app.gymequipment')),
            ],
            bases=('club_app.staff',),
        ),
        migrations.AlterUniqueTogether(
            name='playunit',
            unique_together={('facility', 'unit_num')},
        ),
    ]
