# Generated by Django 6.0.4 on 2026-05-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='member',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='visitor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='visitor',
        ),
        migrations.AddField(
            model_name='booking',
            name='bk_end_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='bk_start_time',
            field=models.TimeField(default='11:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='play_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club_app.playunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='club_app.booking')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='club_app.payment')),
            ],
        ),
        migrations.CreateModel(
            name='MemberBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_booking', to='club_app.booking')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='club_app.member')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payment', to='club_app.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='club_app.membershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_booking', to='club_app.booking')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club_app.visitor')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingDetail',
        ),
    ]
